from MaxHeap import max_heap

mh = max_heap()
mh.insert(5)
mh.insert(6)
mh.insert(1)
mh.insert(11)
mh.insert(20)
print(mh.extract())
print(mh.extract())
print(mh.extract())
print(mh.extract())
print(mh.extract())
print(mh.extract())
print(mh.heap)
