# Generated by Django 2.1.7 on 2019-05-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0002_auto_20190514_2228")]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="p_large",
            field=models.FloatField(blank=True, null=True),
        )
    ]
