# Generated by Django 2.1.7 on 2019-06-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0005_auto_20190602_0819")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(default="Canada", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.IntegerField(default=123456789),
            preserve_default=False,
        ),
    ]
